name: Build and Release Firmware

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download Microchip Studio installer
      run: |
        Invoke-WebRequest -Uri "https://ww1.microchip.com/downloads/en/DeviceDoc/mplabx-ide-5.55-windows-installer.exe" -OutFile "MicrochipStudio.exe"

    - name: Install Microchip Studio
      run: |
        Start-Process -FilePath ".\MicrochipStudio.exe" -ArgumentList "/Silent" -Wait

    - name: Install dependencies
      run: |
        choco install gcc-arm-none-eabi -y
        choco install dfu-programmer -y

    - name: Build project
      run: |
        & 'C:\Program Files (x86)\Microchip\MPLABX\v6.xx\microchip\mplab_platform\bin\microchip-studio.exe' --headless -open "implementations\samd20-optiboot-custom\samd20-optiboot-custom.atsln" -build

    - name: Create release artifact
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p release
        cp implementations/samd20-optiboot-custom/samd20-optiboot-custom/Debug/samd20-optiboot-custom.hex release/samd20-optiboot-custom.hex

    - name: Upload release artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: release/

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: release/samd20-optiboot-custom.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
