name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Package C Assets
      run: |
        tar -czvf bootloader_assets.tar.gz src/*.c src/*.h src/user/* src/deps/embedded-external-flash-memory/*
        tar -czvf hex_writer_assets.tar.gz src/app/*
    - name: Release
      run: |
        version="$(. ./utilities/version/get_version.sh)"
        gh release create "$version" bootloader_assets.tar.gz hex_writer_assets.tar.gz --title "$version" --generate-notes --repo https://github.com/warrenwoolseyiii/embedded-external-flash-memory --target develop
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
